%import common.ESCAPED_STRING -> STRING
%import common.WS
%ignore WS

EQ : "="
LT : "<"
GT : ">"
LTE : "<="
GTE : ">="

op:   EQ
    | LT
    | GT
    | LTE
    | GTE

arg :   comparison 
    |   predicate

comparison: STRING op STRING
fn_and : "AND"i "(" arg [("," arg)*] ")"
fn_or : "OR"i "(" arg [("," arg)*] ")"
fn_not : "NOT"i "(" arg ")"

predicate   :   fn_and
            |   fn_or
            |   fn_not
            |   comparison